@startsalt
{
  使用案例：UC05 VARS 查詢變數 | 情節類型：例外情節 1 — 尚無任何變數
  {#
    **Actor 動作** | **系統回應**
    1. TUCBW：使用者在未執行任何程式的情況下輸入 VARS | 2. 系統嘗試存取直譯器的符號表
    . | 3. 系統發現全域符號表中尚無任何變數
    . | 4. TUCEW：系統顯示「No variables defined」提示訊息
  }
}
@endsalt
